name: azkagram
description: A new Flutter project.
publish_to: 'none'
version: 0.0.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 
  markdown: ^5.0.0
  easy_isolate: ^1.3.0 
  iconsax: ^0.0.8 
  path_provider: ^2.0.11
  hive_flutter: ^1.1.0
  zxing2: ^0.1.0
  image: ^3.2.0
  telegram_client:
    path: /home/hexaminate/Documents/HEXAMINATE/library/telegram_client/dart/telegram_client
  simulate: ^0.0.7
  pull_to_refresh: ^2.0.0
  hidable: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/