name: azkagram
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  telegram_client: ^0.2.6
  markdown: ^4.0.1
  easy_isolate: ^1.3.0
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  simulate: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/