name: Build Cross Platform Artifact
on: [workflow_dispatch]
# There is a single job here called "build" (The word "build" is NOT a keyword, you can use anything there)
jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{ matrix.os }}
    # Just a free-text name to be descriptive
    name: Build App on ${{ matrix.os }}
    steps:
      - name: Build App
        run:   |
          echo "$RUNNER_OS not supported"
        shell: bash